GET http://localhost:8080/teams
Cookie: "access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJwb3JreXRoZWJsYWNrIiwiaWF0IjoxNjU2MzE5MDUzfQ.mkahDZOZUZYsePonj9VEyr6LsN60JuoCLZ7He9YmVO4;"
Content-Type: application/json

{
    "team_name": "cool_cats"
}